BlogWebPage/Controllers/AdminMainController.cs
using BlogWebPage.Models.Entity;
using BlogWebPage.Repositories;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BlogWebPage.Controllers
{
    public class AdminMainController : Controller
    {
        // GET: AdminMain
        readonly GenericRepository<Posts> repo = new GenericRepository<Posts>();
        public ActionResult Index()
        {
            var values = repo.List();
            return View(values);
        }
        public ActionResult AddPost()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddPost(Posts p)
        {
            if (Request.Files.Count > 0)
            {
                string filename = Path.GetFileNameWithoutExtension(Request.Files[0].FileName);
                string extension = Path.GetExtension(Request.Files[0].FileName);
                string ImgFile = "~/Image/" + filename + extension;
                Request.Files[0].SaveAs(Server.MapPath(ImgFile));
                p.Image = "/Image/" + filename + extension;
            }
            p.Date = DateTime.Now;
            p.Status = true;
            repo.Add(p);
            return RedirectToAction("Index");
        }
        public ActionResult EditPost(int id)
        {
            var value = repo.Get(id);
            return View(value);
        }

        [HttpPost]
        public ActionResult EditPost(Posts t)
        {
            var value = repo.Get(t.ID);
            if (Request.Files.Count > 0 && !string.IsNullOrEmpty(Request.Files[0].FileName)) //&& !string.IsNullOrEmpty(Request.Files[0].FileName this code checks whether new img has added or not.
            {
                string filename = Path.GetFileNameWithoutExtension(Request.Files[0].FileName);
                string extension = Path.GetExtension(Request.Files[0].FileName);
                string ImgFile = "~/Image/" + filename + extension;
                Request.Files[0].SaveAs(Server.MapPath(ImgFile));
                value.Image = "/Image/" + filename + extension;
            }
            if (t.Date.HasValue)
            {
                value.Date = t.Date.Value;
            }
            value.Subtitle = t.Subtitle;
            value.Title = t.Title;
            value.Status = true;
            value.Description = t.Description;
            value.MainText = t.MainText;
            repo.Update(value);
            return RedirectToAction("Index");
        }
        public ActionResult PassivePost(int id)
        {
            var values = repo.Find(x => x.ID == id);
            if (values.Status == false)
            {
                values.Status = true;
            }
            else
            {
                values.Status = false;
            }
            repo.Update(values);
            return RedirectToAction("Index");
        }
        public ActionResult DeletePost(int id)
        {
            var values = repo.Find(x => x.ID == id);
            repo.Delete(values);
            return RedirectToAction("Index");
        }

    }
}

BlogWebPage/Views/AdminMain/AddPost.cshtml
@model BlogWebPage.Models.Entity.Posts

@{
    ViewBag.Title = "AddPost";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<style>
    #imagePreview img {
        width: 150px;
        height: 150px;
        object-fit: cover;
    }
</style>

    
<br />
<h2 class="text-center">Yeni Post Ekleme Sayfası</h2>
<br />

@using (Html.BeginForm("AddPost", "AdminMain", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="form-group">
        <label for="Title">Başlık</label>
        <input type="text" id="Title" name="Title" class="form-control mb-2" />

        <label for="Subtitle">Gezi Türü</label>
        <input type="text" id="Subtitle" name="Subtitle" class="form-control mb-2" />

        <label for="Description">Açıklama</label>
        <input id="Description" name="Description" class="form-control mb-2">

        <div class="form-group">
            <label for="Image">Kapak Resmi</label>
            <div class="custom-file">
                <input type="file" class="custom-file-input" id="Image" name="Image" onchange="displayImagePreview(), displayFileName()">
                <label class="custom-file-label" for="Image" id="fileLabel"></label>
            </div>
            <small class="form-text text-muted">En büyük dosya boyutu: 5MB</small>
            <div id="imagePreview" class="mt-2"></div>
        </div>

        <textarea name="MainText" id="editor" rows="10" cols="80"></textarea>
    </div>
    <button class="btn btn-dark mt-2">Gönder</button>
}

<script>
    document.addEventListener('DOMContentLoaded', function () {
        CKEDITOR.replace('MainText', {
            language: 'tr',
            uiColor: '#009CFF',
            height:600,
        });
    });
    function displayImagePreview() {
        const input = document.getElementById('Image');
        const preview = document.getElementById('imagePreview');

        while (preview.firstChild) {
            preview.removeChild(preview.firstChild);
        }

        if (input.files && input.files[0]) {
            const reader = new FileReader();

            reader.onload = function (e) {
                const img = document.createElement('img');
                img.src = e.target.result;
                img.className = 'img-thumbnail';
                preview.appendChild(img);
            };
            reader.readAsDataURL(input.files[0]);
        }
    }

    function displayFileName() {
        const input = document.getElementById('Image');
        const label = document.getElementById('fileLabel');
        const fileName = input.files[0].name;
        label.innerText = fileName;
    }
</script>

BlogWebPage/Views/AdminMain/EditPost.cshtml
@model BlogWebPage.Models.Entity.Posts

@{
    ViewBag.Title = "AddPost";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<style>
    #imagePreview img {
        width: 150px; /* Dilediğin genişlik değerini buraya ekleyebilirsin */
        height: 150px; /* Dilediğin yükseklik değerini buraya ekleyebilirsin */
        object-fit: cover;
    }

</style>


<br />
<h2 class="text-center">Post Düzenleme Sayfası</h2>
<br />

@using (Html.BeginForm("EditPost", "AdminMain", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="form-group ">
        <label for="Title">Başlık</label>
        <input type="text" id="Title" name="Title" class="form-control mb-2" value="@Model.Title" required />

        <label for="Subtitle">Gezi Türü</label>
        <input type="text" id="Subtitle" name="Subtitle" class="form-control mb-2" value="@Model.Subtitle" required />

        <label for="Description">Açıklama</label>
        <input id="Description" name="Description" class="form-control mb-2" value="@Model.Description" required>

        <div class="form-group">
            <label for="Image">Kapak Resmi</label>
            <div class="custom-file">
                <input type="file" class="custom-file-input" id="Image" name="Image" onchange="displayImagePreview(), displayFileName()">
                <label class="custom-file-label" for="Image" id="fileLabel">@Model.Image</label>
                </div>
            <small class="form-text text-muted">En büyük dosya boyutu: 5MB</small>
            <div id="imagePreview" class="mt-2"></div>
        </div>
        <textarea name="MainText" id="editor">@Model.MainText</textarea>
    </div>
    <button class="btn btn-dark mt-2">Gönder</button>

}

<script>
    document.addEventListener('DOMContentLoaded', function () {
        CKEDITOR.replace('MainText', {
            language: 'tr',
            uiColor: '#009CFF',
            height: 600,
        });
    });

    function displayImagePreview() {
        const input = document.getElementById('Image');
        const preview = document.getElementById('imagePreview');

        while (preview.firstChild) {
            preview.removeChild(preview.firstChild);
        }

        if (input.files && input.files[0]) {
            const reader = new FileReader();

            reader.onload = function (e) {
                const img = document.createElement('img');
                img.src = e.target.result;
                img.className = 'img-thumbnail';
                preview.appendChild(img);
            };

            reader.readAsDataURL(input.files[0]);
        }
    }
    function displayFileName() {
        const input = document.getElementById('Image');
        const label = document.getElementById('fileLabel');
        const fileName = input.files[0].name;
        label.innerText = fileName;
    }
</script>

BlogWebPage/Views/AdminMain/Index.cshtml
@using BlogWebPage.Models.Entity
@model List<Posts>


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    int number = 1;
}

<br />
<h2 class="text-center">Yeni Post Ekleme Admin Kontrol Sayfası</h2>
<br />

@if (Model.Count == 0)
{
    <p>No experiences to display.</p>
}
else
{
    <div class="text-center">
        <table class="table table-striped table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th>ID</th>
                    <th>Başlık</th>
                    <th>Gezi Türü</th>
                    <th>Tarih</th>
                    <th>Açıklama</th>
                    <th>Durum</th>
                    <th>Pasif yap</th>
                    <th>Düzenle</th>
                    <th>Sil</th>
                </tr>
            </thead>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@number</td>
                    <td>@item.Title</td>
                    <td>@item.Subtitle</td>
                    <td>@item.Date.Value.ToString("dd MMM yyyy")</td>
                    <td>@item.Description</td>
                    @if (item.Status == true)
                    {
                        <td>Aktif</td>
                    }
                    else
                    {
                        <td>Pasif</td>
                    }
                    <td><a href="/AdminMain/PassivePost/@item.ID" class="btn btn-outline-danger btn-sm"><i class="fas fa-book-reader"></i> Pasif Yap || Aktif Yap</a></td>
                    <td><a href="/AdminMain/EditPost/@item.ID" class="btn btn-info btn-sm"><i class="fas fa-pencil-alt"></i> Düzenle</a></td>
                    <td><a href="/AdminMain/DeletePost/@item.ID" class="btn btn-danger btn-sm"><i class="fas fa-trash"></i> Sil</a></td>
                </tr>
                number++;
            }
        </table>
    </div>
}

<a href="/AdminMain/Addpost/" class="btn btn-dark">Yeni Post</a>