BlogWebPage/Controllers/ImagePageController.cs
using BlogWebPage.Models.Entity;
using BlogWebPage.Repositories;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BlogWebPage.Controllers
{
    public class ImagePageController : Controller
    {
        // GET: ImagePage
        readonly GenericRepository<Images> repo = new GenericRepository<Images>();
        public ActionResult Index()
        {
            var values = repo.List();
            return View(values);
        }
        public ActionResult AddPost()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddPost(Images p)
        {
            if (Request.Files.Count > 0)
            {
                string filename = Path.GetFileNameWithoutExtension(Request.Files[0].FileName);
                string extension = Path.GetExtension(Request.Files[0].FileName);
                string ImgFile = "~/Image/" + filename + extension;
                Request.Files[0].SaveAs(Server.MapPath(ImgFile));
                p.CoverImage = "/Image/" + filename + extension;
            }
            p.Date = DateTime.Now;
            repo.Add(p);
            return RedirectToAction("Index");
        }
        public ActionResult EditPost(int id)
        {
            var value = repo.Get(id);
            return View(value);
        }

        [HttpPost]
        public ActionResult EditPost(Images t)
        {
            var value = repo.Get(t.ID);
            if (Request.Files.Count > 0 && !string.IsNullOrEmpty(Request.Files[0].FileName)) //&& !string.IsNullOrEmpty(Request.Files[0].FileName this code checks whether new img has added or not.
            {
                string filename = Path.GetFileNameWithoutExtension(Request.Files[0].FileName);
                string extension = Path.GetExtension(Request.Files[0].FileName);
                string ImgFile = "~/Image/" + filename + extension;
                Request.Files[0].SaveAs(Server.MapPath(ImgFile));
                value.CoverImage = "/Image/" + filename + extension;
            }
            if (t.Date.HasValue)
            {
                value.Date = t.Date.Value;
            }
            value.Title = t.Title;
            repo.Update(value);
            return RedirectToAction("Index");
        }
        public ActionResult DeletePost(int id)
        {
            var values = repo.Find(x => x.ID == id);
            repo.Delete(values);
            return RedirectToAction("Index");
        }
    }
}

BlogWebPage/Views/ImagePage/AddPost.cshtml
@model BlogWebPage.Models.Entity.Images

@{
    ViewBag.Title = "AddPost";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<style>
    #imagePreview img {
        width: 150px;
        height: 150px;
        object-fit: cover;
    }
</style>


<br />
<h2 class="text-center">Yeni Post Ekleme Sayfası</h2>
<br />

@using (Html.BeginForm("AddPost", "ImagePage", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="form-group">
        <label for="Title">Başlık</label>
        <input type="text" id="Title" name="Title" class="form-control mb-2" />

        <div class="form-group">
            <label for="Image">Kapak Resmi</label>
            <div class="custom-file">
                <input type="file" class="custom-file-input" id="CoverImage" name="CoverImage" onchange="displayImagePreview(), displayFileName()">
                <label class="custom-file-label" for="CoverImage" id="fileLabel"></label>
            </div>
            <small class="form-text text-muted">En büyük dosya boyutu: 5MB</small>
            <div id="imagePreview" class="mt-2"></div>
        </div>
    </div>
    <button class="btn btn-dark mt-2">Gönder</button>
}

<script>
    function displayImagePreview() {
        const input = document.getElementById('CoverImage');
        const preview = document.getElementById('imagePreview');

        while (preview.firstChild) {
            preview.removeChild(preview.firstChild);
        }

        if (input.files && input.files[0]) {
            const reader = new FileReader();

            reader.onload = function (e) {
                const img = document.createElement('img');
                img.src = e.target.result;
                img.className = 'img-thumbnail';
                preview.appendChild(img);
            };
            reader.readAsDataURL(input.files[0]);
        }
    }

    function displayFileName() {
        const input = document.getElementById('CoverImage');
        const label = document.getElementById('fileLabel');
        const fileName = input.files[0].name;
        label.innerText = fileName;
    }
</script>

BlogWebPage/Views/ImagePage/EditPost.cshtml
@model BlogWebPage.Models.Entity.Images

@{
    ViewBag.Title = "AddPost";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<style>
    #imagePreview img {
        width: 150px; /* Dilediğin genişlik değerini buraya ekleyebilirsin */
        height: 150px; /* Dilediğin yükseklik değerini buraya ekleyebilirsin */
        object-fit: cover;
    }
</style>


<br />
<h2 class="text-center">Post Düzenleme Sayfası</h2>
<br />

@using (Html.BeginForm("EditPost", "ImagePage", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="form-group ">
        <label for="Title">Başlık</label>
        <input type="text" id="Title" name="Title" class="form-control mb-2" value="@Model.Title" required />
        <div class="form-group">
            <label for="Image">Kapak Resmi</label>
            <div class="custom-file">
                <input type="file" class="custom-file-input" id="CoverImage" name="CoverImage" onchange="displayImagePreview(), displayFileName()">
                <label class="custom-file-label" for="CoverImage" id="fileLabel">@Model.CoverImage</label>
            </div>
            <small class="form-text text-muted">En büyük dosya boyutu: 5MB</small>
            <div id="imagePreview" class="mt-2"></div>
        </div>
    </div>
    <button class="btn btn-dark mt-2">Gönder</button>

}

<script>
    function displayImagePreview() {
        const input = document.getElementById('CoverImage');
        const preview = document.getElementById('imagePreview');

        while (preview.firstChild) {
            preview.removeChild(preview.firstChild);
        }

        if (input.files && input.files[0]) {
            const reader = new FileReader();

            reader.onload = function (e) {
                const img = document.createElement('img');
                img.src = e.target.result;
                img.className = 'img-thumbnail';
                preview.appendChild(img);
            };

            reader.readAsDataURL(input.files[0]);
        }
    }
    function displayFileName() {
        const input = document.getElementById('CoverImage');
        const label = document.getElementById('fileLabel');
        const fileName = input.files[0].name;
        label.innerText = fileName;
    }
</script>

BlogWebPage/Views/ImagePage/Index.cshtml
@using BlogWebPage.Models.Entity
@model List<Images>


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    int number = 1;
}

<br />
<h2 class="text-center">Yeni Resim Ekleme Admin Kontrol Sayfası</h2>
<br />

@if (Model.Count == 0)
{
    <p>No experiences to display.</p>
}
else
{
    <div class="text-center">
        <table class="table table-striped table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th>ID</th>
                    <th>Başlık</th>
                    <th>Tarih</th>
                    <th>Düzenle</th>
                    <th>Sil</th>
                </tr>
            </thead>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@number</td>
                    <td>@item.Title</td>
                    <td>@item.Date.Value.ToString("dd MMM yyyy")</td>
                    <td><a href="/ImagePage/EditPost/@item.ID" class="btn btn-info btn-sm"><i class="fas fa-pencil-alt"></i> Düzenle</a></td>
                    <td><a href="/ImagePage/DeletePost/@item.ID" class="btn btn-danger btn-sm"><i class="fas fa-trash"></i> Sil</a></td>
                </tr>
                number++;
            }
        </table>
    </div>
}

<a href="/ImagePage/Addpost/" class="btn btn-dark">Yeni Post</a>